services:
  new-easyepg:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: "Dockerfile.amd64"
    container_name: new-easyepg
    environment:
      - PUID=99
      - PGID=100
      - TIMEZONE=Europe/Berlin
      - UPDATE=yes
      - REPO=script.service.easyepg-lite
      - BRANCH=main
    volumes:
      - easyepg:/easyepg
      - easyepg_xml:/easyepg/xml
    tmpfs:
      - /var/log
      - /tmp
    ports:
      - 4000:4000
    restart: unless-stopped
volumes:
  easyepg:
  easyepg_xml: